### ISSUE TITLE
exponentialDelay doesnt work.

### ISSUE THREAD

**Issue by lawloretienne** [lifeomic/bitrise#5]
I tried adding exponentialDelay like you have done here
https://github.com/lifeomic/bitrise/blob/856321bfb712d8dd22d310986536b3d9b20a7128/src/client.js#L14

but the the latest version of the axios-retry package doesnt recognize this.  How did you get this to work?

**Comment by mdlavin** [comment]
I'm going to close this because I believe it should be working. Let me know if you are continuing to see problems
